// 國家／地區中文→英文對照（LIFF 英文模式顯示用）。
// 自動產生：scripts/gen-country-names.mjs 讀 data/country-names.xlsx；請勿手改。
// 更新方式：替換 data/country-names.xlsx 後重跑 `node scripts/gen-country-names.mjs`。共 261 筆。
export const COUNTRY_NAME_EN: Record<string, string> = {
  "土耳其": "Türkiye",
  "中英": "China & United Kingdom",
  "中國大陸": "China",
  "中港澳": "China, Hong Kong & Macao",
  "日本": "Japan",
  "日韓": "Japan & Korea",
  "印尼": "Indonesia",
  "印度": "India",
  "沙烏地阿拉伯": "Saudi Arabia",
  "孟加拉": "Bangladesh",
  "波斯灣": "Persian Gulf",
  "阿聯酋": "United Arab Emirates",
  "非洲": "Africa",
  "俄羅斯": "Russia",
  "南美": "South America",
  "柬埔寨": "Cambodia",
  "美加墨": "United States, Canada & Mexico",
  "美國": "United States",
  "泰國": "Thailand",
  "紐澳": "New Zealand & Australia",
  "斯里蘭卡": "Sri Lanka",
  "港澳": "Hong Kong & Macao",
  "菲律賓": "Philippines",
  "越南": "Vietnam",
  "塞班、關島": "Saipan & Guam",
  "新加坡": "Singapore",
  "新馬": "Singapore & Malaysia",
  "蒙古": "Mongolia",
  "寮國": "Laos",
  "摩洛哥": "Morocco",
  "歐洲": "Europe",
  "澳洲": "Australia",
  "韓國": "Korea",
  "台灣": "Taiwan",
  "香港": "Hong Kong",
  "澳門": "Macao",
  "北韓": "North Korea",
  "馬來西亞": "Malaysia",
  "汶萊": "Brunei",
  "緬甸": "Myanmar",
  "東帝汶": "Timor-Leste",
  "巴基斯坦": "Pakistan",
  "尼泊爾": "Nepal",
  "不丹": "Bhutan",
  "馬爾地夫": "Maldives",
  "阿富汗": "Afghanistan",
  "哈薩克": "Kazakhstan",
  "烏茲別克": "Uzbekistan",
  "土庫曼": "Turkmenistan",
  "吉爾吉斯": "Kyrgyzstan",
  "塔吉克": "Tajikistan",
  "喬治亞": "Georgia",
  "亞美尼亞": "Armenia",
  "亞塞拜然": "Azerbaijan",
  "賽普勒斯": "Cyprus",
  "以色列": "Israel",
  "巴勒斯坦": "Palestine",
  "約旦": "Jordan",
  "黎巴嫩": "Lebanon",
  "敘利亞": "Syria",
  "伊拉克": "Iraq",
  "伊朗": "Iran",
  "卡達": "Qatar",
  "科威特": "Kuwait",
  "巴林": "Bahrain",
  "阿曼": "Oman",
  "葉門": "Yemen",
  "英國": "United Kingdom",
  "愛爾蘭": "Ireland",
  "法國": "France",
  "德國": "Germany",
  "荷蘭": "Netherlands",
  "比利時": "Belgium",
  "盧森堡": "Luxembourg",
  "瑞士": "Switzerland",
  "奧地利": "Austria",
  "義大利": "Italy",
  "西班牙": "Spain",
  "葡萄牙": "Portugal",
  "丹麥": "Denmark",
  "瑞典": "Sweden",
  "挪威": "Norway",
  "芬蘭": "Finland",
  "冰島": "Iceland",
  "波蘭": "Poland",
  "捷克": "Czechia",
  "斯洛伐克": "Slovakia",
  "匈牙利": "Hungary",
  "羅馬尼亞": "Romania",
  "保加利亞": "Bulgaria",
  "希臘": "Greece",
  "克羅埃西亞": "Croatia",
  "斯洛維尼亞": "Slovenia",
  "塞爾維亞": "Serbia",
  "波士尼亞與赫塞哥維納": "Bosnia and Herzegovina",
  "黑山／蒙特內哥羅": "Montenegro",
  "北馬其頓": "North Macedonia",
  "阿爾巴尼亞": "Albania",
  "科索沃": "Kosovo",
  "愛沙尼亞": "Estonia",
  "拉脫維亞": "Latvia",
  "立陶宛": "Lithuania",
  "白俄羅斯": "Belarus",
  "烏克蘭": "Ukraine",
  "摩爾多瓦": "Moldova",
  "馬爾他": "Malta",
  "安道爾": "Andorra",
  "摩納哥": "Monaco",
  "列支敦斯登": "Liechtenstein",
  "聖馬利諾": "San Marino",
  "梵蒂岡": "Vatican City",
  "法羅群島": "Faroe Islands",
  "格陵蘭": "Greenland",
  "直布羅陀": "Gibraltar",
  "曼島": "Isle of Man",
  "澤西": "Jersey",
  "根西": "Guernsey",
  "奧蘭群島": "Åland Islands",
  "斯瓦爾巴與揚馬延": "Svalbard and Jan Mayen",
  "加拿大": "Canada",
  "墨西哥": "Mexico",
  "瓜地馬拉": "Guatemala",
  "貝里斯": "Belize",
  "宏都拉斯": "Honduras",
  "薩爾瓦多": "El Salvador",
  "尼加拉瓜": "Nicaragua",
  "哥斯大黎加": "Costa Rica",
  "巴拿馬": "Panama",
  "巴哈馬": "Bahamas",
  "古巴": "Cuba",
  "牙買加": "Jamaica",
  "海地": "Haiti",
  "多明尼加共和國": "Dominican Republic",
  "安地卡及巴布達": "Antigua and Barbuda",
  "多米尼克": "Dominica",
  "聖克里斯多福及尼維斯": "Saint Kitts and Nevis",
  "聖露西亞": "Saint Lucia",
  "聖文森及格瑞那丁": "Saint Vincent and the Grenadines",
  "巴貝多": "Barbados",
  "格瑞那達": "Grenada",
  "千里達及托巴哥": "Trinidad and Tobago",
  "波多黎各": "Puerto Rico",
  "美屬維京群島": "U.S. Virgin Islands",
  "英屬維京群島": "British Virgin Islands",
  "安圭拉": "Anguilla",
  "蒙特塞拉特": "Montserrat",
  "開曼群島": "Cayman Islands",
  "百慕達": "Bermuda",
  "特克斯和凱科斯群島": "Turks and Caicos Islands",
  "阿魯巴": "Aruba",
  "庫拉索": "Curaçao",
  "波奈": "Bonaire",
  "聖尤斯特歇斯": "Sint Eustatius",
  "薩巴": "Saba",
  "荷屬聖馬丁": "Sint Maarten",
  "法屬聖馬丁": "Saint Martin",
  "聖巴瑟米": "Saint Barthélemy",
  "瓜德羅普": "Guadeloupe",
  "馬丁尼克": "Martinique",
  "聖皮耶與密克隆": "Saint Pierre and Miquelon",
  "巴西": "Brazil",
  "阿根廷": "Argentina",
  "智利": "Chile",
  "秘魯": "Peru",
  "哥倫比亞": "Colombia",
  "委內瑞拉": "Venezuela",
  "厄瓜多": "Ecuador",
  "玻利維亞": "Bolivia",
  "巴拉圭": "Paraguay",
  "烏拉圭": "Uruguay",
  "蓋亞那": "Guyana",
  "蘇利南": "Suriname",
  "法屬圭亞那": "French Guiana",
  "福克蘭群島": "Falkland Islands",
  "埃及": "Egypt",
  "利比亞": "Libya",
  "突尼西亞": "Tunisia",
  "阿爾及利亞": "Algeria",
  "西撒哈拉": "Western Sahara",
  "蘇丹": "Sudan",
  "南蘇丹": "South Sudan",
  "衣索比亞": "Ethiopia",
  "厄利垂亞": "Eritrea",
  "吉布地": "Djibouti",
  "索馬利亞": "Somalia",
  "肯亞": "Kenya",
  "烏干達": "Uganda",
  "坦尚尼亞": "Tanzania",
  "盧安達": "Rwanda",
  "蒲隆地": "Burundi",
  "剛果民主共和國": "Democratic Republic of the Congo",
  "剛果共和國": "Republic of the Congo",
  "中非共和國": "Central African Republic",
  "查德": "Chad",
  "喀麥隆": "Cameroon",
  "奈及利亞": "Nigeria",
  "尼日": "Niger",
  "貝南": "Benin",
  "多哥": "Togo",
  "迦納": "Ghana",
  "象牙海岸": "Côte d'Ivoire",
  "賴比瑞亞": "Liberia",
  "獅子山": "Sierra Leone",
  "幾內亞": "Guinea",
  "幾內亞比索": "Guinea-Bissau",
  "塞內加爾": "Senegal",
  "甘比亞": "Gambia",
  "茅利塔尼亞": "Mauritania",
  "馬利": "Mali",
  "布吉納法索": "Burkina Faso",
  "維德角": "Cabo Verde",
  "赤道幾內亞": "Equatorial Guinea",
  "加彭": "Gabon",
  "聖多美普林西比": "São Tomé and Príncipe",
  "安哥拉": "Angola",
  "尚比亞": "Zambia",
  "辛巴威": "Zimbabwe",
  "馬拉威": "Malawi",
  "莫三比克": "Mozambique",
  "納米比亞": "Namibia",
  "波札那": "Botswana",
  "南非": "South Africa",
  "賴索托": "Lesotho",
  "史瓦帝尼": "Eswatini",
  "馬達加斯加": "Madagascar",
  "模里西斯": "Mauritius",
  "塞席爾": "Seychelles",
  "葛摩": "Comoros",
  "留尼旺": "Réunion",
  "馬約特": "Mayotte",
  "聖赫勒拿": "Saint Helena",
  "紐西蘭": "New Zealand",
  "巴布亞紐幾內亞": "Papua New Guinea",
  "斐濟": "Fiji",
  "索羅門群島": "Solomon Islands",
  "萬那杜": "Vanuatu",
  "薩摩亞": "Samoa",
  "美屬薩摩亞": "American Samoa",
  "東加": "Tonga",
  "吐瓦魯": "Tuvalu",
  "吉里巴斯": "Kiribati",
  "諾魯": "Nauru",
  "帛琉": "Palau",
  "密克羅尼西亞聯邦": "Federated States of Micronesia",
  "馬紹爾群島": "Marshall Islands",
  "關島": "Guam",
  "北馬里亞納群島": "Northern Mariana Islands",
  "塞班島": "Saipan",
  "新喀里多尼亞": "New Caledonia",
  "法屬玻里尼西亞": "French Polynesia",
  "庫克群島": "Cook Islands",
  "紐埃": "Niue",
  "托克勞": "Tokelau",
  "諾福克島": "Norfolk Island",
  "瓦利斯和富圖納": "Wallis and Futuna",
  "皮特肯群島": "Pitcairn Islands",
  "聖誕島": "Christmas Island",
  "科科斯（基林）群島": "Cocos (Keeling) Islands",
  "英屬印度洋領地": "British Indian Ocean Territory",
  "南喬治亞與南桑威奇群島": "South Georgia and the South Sandwich Islands",
  "塞班": "Saipan",
}

// 英文模式取國名：命中對照表→回英文；未命中→退回傳入的 countryNameEn（若有）→中文原名。
export function enCountryName(zh: string, fallbackEn?: string | null): string {
  return COUNTRY_NAME_EN[(zh ?? '').trim()] || fallbackEn || zh
}
